---
title: "STA 360: Bayesian methods and modern statistics"
subtitle: "Fall 2023"
mainfont: Lato
format: 
   html: 
    page-layout: full
    toc: true
---

# Syllabus

### Course description

This course introduces Bayesian modeling and inference, motivated by real world examples.
Course topics include Bayes' theorem, exchangeability, conjugate priors, Markov chain Monte Carlo (MCMC) approximation, Gibbs sampling, hierarchical modeling, Bayesian regression and generalized linear models. 
We compare and contrast Bayesian methods to the frequentist paradigm.
By the end of this course students should feel comfortable (1) writing Bayesian models and, when appropriate, (2) sampling from the posterior using MCMC to make inference. 

### Logistics

{{< include _logistics.qmd >}}

Course website: [sta360-fa23.github.io](https://sta360-fa23.github.io/)

<!-- - Dr. Alexander Fisher (lecturer), office hours Old Chem 207 -->
<!--   - Lecture:  -->
<!-- - TBD (TA) -->
<!--   - Lab:  -->
<!-- - TBD (TA) -->
<!--   - Lab:  -->

### Course material

- [A First Course in Bayesian Statistical Methods](https://pdhoff.github.io/book/). As a Duke student, an electronic version of the book is freely available to you on Springer link. Check the errata at the link above.

- [Chapter summaries](/chapterSummaries.html). I compile major take-away points from each section. Review these to help prepare for exams.

- We will use the statistical software package R on homework asignments in this course. R is freely available at [http://www.r-project.org/](http://www.r-project.org/).
RStudio, the popular IDE for R, is freely available at [https://posit.co/downloads/](https://posit.co/downloads/).

### Schedule of topics

Part I: The Bayesian modeling toolkit

1. Review of probability
2. Conjugate statistical models
3. Semi-conjugate models and Gibbs sampling

Part II: Statistical model building and analysis

1. Multilevel models
2. Linear regression
3. Generalized linear models
4. Density estimation and classification

### Evaluation

| Assignment          | Description                        |
|---------------------|------------------------------------|
| Homework (40%)          | Individual take-home assignments, submitted to Gradescope.      |
| Midterms (30%)         | Two in-class exams.    |
| Final exam (25%) | Cumulative final during final's week.   |
| Quizzes (5%)       | In-class pop quizzes.         |

A $>= 93$, A- $< 93$, B+ $< 90$, B $< 87$, B- $< 83$, C+ $<80$, C $< 77$, C- $< 73$, D+ $< 70$, D $< 67$, D- $< 63$, F $< 60$

::: {.callout-note}
# A note on quizzes
On random class days, there will be a brief quiz on the previous lectures. If you score  $>60\%$ cumulatively on your final quiz grade, you will receive full participation credit. Your lowest **two** quizzes will also be dropped.
:::

::: {.callout-note}
# A note on exams
If you miss either midterm 1 or midterm 2, **and have an excused absence**, your missing midterm grade will be replaced by your final exam grade. You must take at least 1 midterm and the final exam to pass the course.
:::

<!-- ::: {.callout-important} -->
<!-- # Late work -->
<!-- Late homework may be submitted with 48 hours of the assignment deadline. Late homework submitted within 24 hours (even 1 minute late) will receive a 5% late penalty. Late work submitted between 24 to 48 hours of the deadline will receive a 10% late penalty. Work submitted after 48 hours will not be accepted. Exams cannot be turned in late and can only be excused under exceptional circumstances. The Duke policy for illness requires a short-term illness report or a letter from the Dean; except in emergencies, all other absenteeism must be approved in advance (e.g., an athlete who must miss class may be excused by prior arrangement for specific days). For emergencies, email notification is needed at the first reasonable time. -->
<!-- ::: -->

### Policies

**Academic integrity**

By enrolling in this course, you commit to upholding Duke's community standard reproduced as follows:

> I will not lie, cheat, or steal in my academic endeavors;
>
I will conduct myself honorably in all my endeavors; and
>
I will act if the Standard is compromised.

Any violations of academic integrity will automatically result in a 0 for the assignment and will be reported to the Office of Student Conduct for further action. For the Exams and Quizzes, students are required to work alone. For the Homework assignments, students may work with a study group but each student must write up and submit their own answers.

**Late work**

Late homework may be submitted within 48 hours of the assignment deadline. Late homework submitted within 24 hours (even 1 minute late) will receive a 5% late penalty. Late work submitted between 24 to 48 hours of the deadline will receive a 10% late penalty. Work submitted after 48 hours will not be accepted. Exams cannot be turned in late and can only be excused under exceptional circumstances. The Duke policy for illness requires a short-term illness report or a letter from the Dean; except in emergencies, all other absenteeism must be approved in advance (e.g., an athlete who must miss class may be excused by prior arrangement for specific days). For emergencies, email notification is needed at the first reasonable time.


**Errors in grading**

Errors in grading must be brought to the attention of the TA or instructor during office hours within 1 week of receiving the grade.


