---
title: "Homework 6"
subtitle: "Due Friday November 1st at 5:00pm"
mainfont: Lato
format: 
  html:
    toc: true
---

## Exercise 1


6.2 from Hoff. Note the typo: $1/\sigma_j^2$ is gamma, not $1/\sigma_j$. Use the code below to load the data.

```{r}
#| eval: false

glucose = readr::read_csv("https://sta360-fa24.github.io/data/glucose.csv")

```


## Exercise 2

Recall that if $W \sim \text{Wishart}_p(m, S)$ then $W = \sum_{i=1}^m z_i z_i^T$ where $z_1, \ldots, z_m \sim \text{i.i.d. } N_p(0, S)$

a. Show that $E[W] = mS$.

b. Show that $W$ is positive definite if $m \geq p$. 

## Exercise 3

Suppose $Y$ is a random normal vector $Y \sim N_p(\theta, \Sigma)$. Let $Y_A$ be the first $p_1$ elements of $Y$ and $Y_B$ be the last $p_2 = p - p_1$ elements, so that $Y = (Y_A, Y_B)$. Similarly, write $\theta = (\theta_A, \theta_B)$. Finally, let 

$$
\Sigma^{-} \equiv \Psi = \left[ {\begin{array}{cc}
   \Psi_{AA} & \Psi_{AB} \\
   \Psi_{BA} & \Psi_{BB} \\
  \end{array} } \right]
$$
and note that $\Psi_{AB} = \Psi_{BA}^T$. Find the conditional distribution of $Y_B$ given $Y_A$ in terms of $\theta_A$, $\theta_B$ and components of $\Psi$. Try to interpret how $E[Y_B|Y_A]$ differs from $E[Y_B]$ and how $V[Y_B|Y_A]$ differs from $V[Y_B]$.

### Identities for exercise 3

Some of the following identities will be helpful for *interpretation*.

Let 

$$
\Sigma = \left[ {\begin{array}{cc}
   \Sigma_{AA} & \Sigma_{AB} \\
   \Sigma_{BA} & \Sigma_{BB} \\
  \end{array} } \right]
$$

and

$$
\Psi = \left[ {\begin{array}{cc}
   \Psi_{AA} & \Psi_{AB} \\
   \Psi_{BA} & \Psi_{BB} \\
  \end{array} } \right].
$$

Then 

$$
\begin{aligned}
\Psi_{AA}^- &= \Sigma_{AA} - \Sigma_{AB} \Sigma_{BB}^- \Sigma_{BA}\\
\Psi_{BB}^- &= \Sigma_{BB} - \Sigma_{BA} \Sigma_{AA}^- \Sigma_{AB}\\
\Psi_{AB} &= -\Psi_{AA} \Sigma_{AB} \Sigma_{BB}^-\\
\Psi_{BA} &= -\Psi_{BB} \Sigma_{BA} \Sigma_{AA}^-,
\end{aligned}
$$

and note that $\Sigma_{AB} = \Sigma_{BA}^T$ and $\Psi_{AB} = \Psi_{BA}^T$.