---
title: "Homework 9"
subtitle: "Due Friday December 6 at 5:00pm"
mainfont: Lato
format: 
  html:
    toc: true
---

```{r}
#| code-fold: true
#| code-summary: load-libraries
#| warning: false
#| message: false
library(tidyverse)
```


## Exercise 1

3.12 from Hoff.


## Exercise 2

8.1 from Hoff. Note there is a typo in this exercise. Every $\theta_i$ in the exercise prompt should be replaced by $\theta_j$.


## Exercise 3

8.3 from Hoff: find the problem setup (definitions of each Greek letter) on page 132 and 132 of the book. Also see, e.g. the [notes on hierarchical modeling](https://sta360-fa24.github.io/notes/lec15-hierarchical-intro.html).

Run the code below to load the data.

```{r}
#| eval: false
library(readr)
library(glue)

for(i in 1:8) {
assign(paste0("school", i), 
       read_csv(glue("https://sta360-fa24.github.io/data/school{i}.csv")))
}
```


<!-- hierarchical modeling -->

<!--dynamical systems -->

<!-- stan -->

<!--
open ended q: breast cancer prediction
https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original -->
